# Generated by Django 5.0.4 on 2024-04-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, related_name='albums', to='api.image'),
        ),
    ]
